# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build all masters
    - name: Build all masters
      run: python3 build.py golven && python3 build.py chemie && python3 build.py milieu && python3 build.py analyse && python3 build.py mechanica && python3 build.py formules

    # Build chemie
    - name: LaTeX Action Chemie
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: chemie/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: chemfig amsmath babel mhchem # optional
     
    - uses: actions/upload-artifact@v2
      with:
        name: chemiepdf
        path: chemie/master.pdf

    # Build golven
    - name: LaTeX Action Golven
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: golven/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: amsmath babel # optional
    
    - uses: actions/upload-artifact@v2
      with:
        name: golvenpdf
        path: golven/master.pdf
        
    # Build milieu
    - name: LaTeX Action Milieu
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: milieu/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: amsmath babel # optional
    
    - uses: actions/upload-artifact@v2
      with:
        name: miliepdf
        path: milieu/master.pdf
        
    # Build analyse
    - name: LaTeX Action Analyse
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: analyse/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: amsmath babel # optional
    
    - uses: actions/upload-artifact@v2
      with:
        name: analysepdf
        path: analyse/master.pdf
        
    # Build Mechanica        
    - name: LaTeX Action Mechanica
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: mechanica/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: amsmath babel # optional
    
    - uses: actions/upload-artifact@v2
      with:
        name: mechanicapdf
        path: mechanica/master.pdf
    
    # Build Formularium        
    - name: LaTeX Action Formularium
      uses: fudan-mse/latex-action@v0.0.1
      with:
        # The root LaTeX file to be compiled
        root_file: master.tex
        # The working directory for the LaTeX engine
        working_directory: formules/ # optional
        # The LaTeX engine to be invoked
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: -pdf -file-line-error -interaction=nonstopmode # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # Install extra packages by tlmgr
        extra_packages: amsmath babel physics # optional
    
    - uses: actions/upload-artifact@v2
      with:
        name: formulariumpdf
        path: formules/master.pdf
